### ISSUE TITLE
Maximum size of tree??

### ISSUE THREAD

**Issue by jrtaylor-3** [T-F-S/genealogytree#8] opened 2017-04-27 18:22 UTC
I suspect that I am bumping up against a size maximum but I would like to know for sure.   I have been having good results using MikTex 64 bit up to about 4 generations.  Once I go beyond that I get the following:

l.33 \end{genealogypicture}
                           
I can't evaluate this expression,
since the result is out of range.

! Arithmetic overflow.
<to be read again> 
                   }
l.33 \end{genealogypicture}
                           
(That makes 100 errors; please try again.) 
Here is how much of TeX's memory you used:
 48100 strings out of 427841
 950277 string characters out of 3152544
 7698400 words of memory out of 9560766
 51553 multiletter control sequences out of 15000+200000
 4008 words of font info for 60 fonts, out of 3000000 for 9000
 1328 hyphenation exceptions out of 8191
 88i,13n,140p,10389b,12747s stack positions out of 5000i,500n,10000p,200000b,50000s
 
This could easily be a problem on my end but I need a pointer in the right direction for debugging.

**Comment by T-F-S** [comment] 2017-04-28 05:44
Your log indicates that the problem is not related to TeX's memory. In my own experience, I also had no problems with TeX's memory and large trees.

But, there is a geometry restriction in TikZ coming from TeX's length register size. Length values are restricted to be in the range between -575.83cm and 575.83cm. Since many calculations start with initial register values of 0pt, it is quite likely that you get errors as your tree grows larger than 5m in width or height. I cannot surpass this restriction with `genealogytree`.

You could try the following circumvention: If you downscale every length of your tree (box size, font size, distances), then it should be possible to have trees with more nodes (as long as the overall size stays small enough).

**Comment by jrtaylor-3** [comment] 2017-04-29 20:29
Thomas,
  I have created a LaTeX report plugin for the Webtrees genealogy system so I am trying to get a handle on the maximum sizes.  Using my personal family tree I get 6 generations in 182x32cm and 7 generations (about 500 nodes) blows up.   I downscaled the tree as recommend and it will now properly process so size was indeed the issue.  Is there a proportional scaling factor that covers all the dimensions?  I like the look of the “portrait” template and  I have managed to get a downsized version to look attractive.

**Comment by Ri-Ga** [comment] 2017-04-29 21:31
Hi John,

for your purposes my genealogytree module "largetrees" (https://github.com/Ri-Ga/gtrlib.largetrees / http://www.ctan.org/pkg/gtrlib-largetrees) might be interesting. It helps you automatically rotating boxes with sparse information (which you might have frequently the more generations you go to the past). I personally used it for almost 400 nodes IIRC. My primary goal there was "shall fit on DIN-A4" rather than "should not produce LaTeX errors", though :-)
In case you give my module a try, I'd be happy to hear about some feedback!

**Comment by jrtaylor-3** [comment] 2017-04-29 23:32
Interesting results from some testing.  Using the code below:
\documentclass{standalone}
\usepackage[all]{genealogytree}
\usepackage{grffile}

\begin{document}
\hyphenpenalty=10000
\gtrset{date format=yyyy.mm.dd}
\begin{genealogypicture}[template=database portrait,
                node size = 0.91cm,
                level size = 4cm,
                level distance=5mm,
                parent distance in child graph=2mm ]
                input{descendantsChart}
\end{genealogypicture}
\end{document}

I generated a tree that was 282cm by 32cm.  The photos looked awful but it created the tree.  When I changed the node size to 0.92cm it failed.   I would have thought that I had at least another 150cm of space to go.

**Comment by T-F-S** [comment] 2017-05-02 05:25
There is a `scale` option to resize a `tikzpicture` completely. I have not tried yet, but I suspect that this will not help to avoid intermediate dimensions which are too large.
Otherwise, there is no other global scale parameter to shrink a graph.

Your testing result is interesting, but it is difficult to say, why the last 150cm cannot be used. My only guess is that some intermediate dimensions are too large...

**Comment by jrtaylor-3** [comment] 2017-05-02 16:58
I played around with the tikzpicture scaling and as you guessed it did not help.  For the moment I will just add some guidance to the users of my plugin.  I really appreciate your help and thank you for putting this package together.  I don’t suppose you have a “fan” format chart package that uses the same data format?  Please close this issue.

**Comment by T-F-S** [comment] 2017-05-03 07:33
I will close this issue as you suggested.

For a "fan" format, I have some home-brewed stuff which currently is not compatible with the `genealogytree` format. But I think it could be made compatible with time enough to implement... Maybe, not so a bad idea.

**Closed as completed by T-F-S** 2017-05-03 07:33 UTC
